In [2]:
import pandas as pd

### Letterboxd Watchlist

In [89]:
df_watchlist = pd.read_csv(
    "data/watchlist-ironscavenger-2026-08-21-08-35-utc.csv"
    )

df_watchlist.columns = [col.lower() for col in df_watchlist.columns]

df_watchlist

           date                              name  year        letterboxd uri
0    2024-02-04      Colossus: The Forbin Project  1970  https://boxd.it/1Nmw
1    2024-02-04                               Her  2013  https://boxd.it/4O24
2    2024-02-04  Once Upon a Time... in Hollywood  2019  https://boxd.it/gH0O
3    2024-02-04                          Napoleon  2023  https://boxd.it/shJM
4    2024-02-04                     Asteroid City  2023  https://boxd.it/s3ds
..          ...                               ...   ...                   ...
348  2026-08-20                        The Chaser  2008  https://boxd.it/1PgU
349  2026-08-20                   I Saw the Devil  2010   https://boxd.it/FaK
350  2026-08-20                            Mother  2009  https://boxd.it/1m9g
351  2026-08-20                     The Innocents  2021  https://boxd.it/oAlc
352  2026-08-21                   Wild Horse Nine  2026  https://boxd.it/xG0M

[353 rows x 4 columns]

### All movies and runtimes

In [106]:
# ----------------------------------------
# Get all movies
df_all_movies = pd.read_csv(
    "data/omdb/all_movies.csv",
    usecols=range(4),
    )

# ----------------------------------------
# Get all movie details
df_movie_details = pd.read_csv(
    "data/omdb/movie_details.csv",
    usecols=range(4),
)

# ----------------------------------------
# Get all movie votes
df_movie_votes = pd.read_csv(
    "data/omdb/all_votes.csv",
    usecols=range(3),
    )

# ----------------------------------------
# Join details with movies
df_all_movies = (
    df_all_movies
    .merge(
        df_movie_details,
        how='left',
        left_on='id',
        right_on='movie_id'
        )
    .drop(columns=['id','parent_id'])
)

# ----------------------------------------
# Join votes with movies
df_all_movies = (
    df_all_movies
    .merge(
        df_movie_votes,
        how='left',
        on='movie_id'
    )
)

# ----------------------------------------
# Convert date-column to actual datetime

# Replace "\N" entries with actual Nulls
sel = df_all_movies['date'] == "\\N"
df_all_movies.loc[sel,'date'] = pd.NA
# Convert values
df_all_movies['date'] = pd.to_datetime(df_all_movies['date'], format='%Y-%m-%d')

df_all_movies

,name,date,movie_id,runtime,budget,revenue,vote_average,votes_count
0,Ariel,1988-10-21,2.0,69.0,0,0,8.000000,3.0
1,Varjoja paratiisissa,1986-10-17,3.0,71.0,0,0,7.800000,5.0
2,État de siège,1972-12-30,4.0,115.0,0,8000000,7.750000,4.0
3,Four Rooms,1995-12-22,5.0,98.0,4000000,4300000,6.478261,23.0
4,Judgment Night,1993-10-15,6.0,110.0,0,0,9.000000,1.0
...,...,...,...,...,...,...,...,...
77539,Nos frangins,2022-05-23,299965.0,92.0,0,0,NaN,NaN
77540,Una notte da dottore,2021-10-28,299967.0,94.0,0,0,NaN,NaN
77541,L'Esprit Coubertin,2024-05-08,299968.0,78.0,2500000,0,6.000000,1.0
77542,Ёлки лохматые,2015-01-29,299969.0,90.0,0,2234206,NaN,NaN
77543,Gone Mom,2021-06-05,300011.0,88.0,0,0,NaN,NaN

### Movie categories

In [ ]:
# ----------------------------------------
# Get all movie categories
df_movie_categories = pd.read_csv(
    "data/omdb/movie_categories.csv",
    usecols=range(2),
    )

# ----------------------------------------
# Get category names
df_category_names = pd.read_csv(
    "data/omdb/category_names.csv",
    usecols=range(3),
    )

# ----------------------------------------
# Only select english category names and drop language column
df_category_names = (
    df_category_names[df_category_names['language_iso_639_1']=='en']
    .drop(columns='language_iso_639_1')
)

# ----------------------------------------
# Join category names with IDs
df_movie_categories = (
    df_movie_categories
    .merge(
        df_category_names,
        on='category_id',
        how='left'
    )
    .rename(columns={'name':'category_name'})
)

# ----------------------------------------
# Join movie names with categories
df_movie_categories = (
    df_movie_categories
    .merge(
        df_all_movies[['movie_id', 'name']],
        on='movie_id'
    )
    .sort_values(['movie_id','category_id'])
)

df_movie_categories

        movie_id  category_id       category_name                  name
111802         2           44        Social Drama                 Ariel
261781         2         3163        Auteur movie                 Ariel
111860         3           44        Social Drama  Varjoja paratiisissa
151999         4          106  Political Thriller         État de siège
185605         4          329           Flashback         État de siège
...          ...          ...                 ...                   ...
13503     299969           17         Family Film         Ёлки лохматые
13504     299969           17        Familienfilm         Ёлки лохматые
53087     300011           18               Drama              Gone Mom
53088     300011           18               Drama              Gone Mom
134083    300011           80               Crime              Gone Mom

[417244 rows x 4 columns]

---

## XXX

In [82]:
df_all_movies

                       name       date  movie_id  runtime   budget  revenue
0                     Ariel 1988-10-21       2.0     69.0        0        0
1      Varjoja paratiisissa 1986-10-17       3.0     71.0        0        0
2             État de siège 1972-12-30       4.0    115.0        0  8000000
3                Four Rooms 1995-12-22       5.0     98.0  4000000  4300000
4            Judgment Night 1993-10-15       6.0    110.0        0        0
...                     ...        ...       ...      ...      ...      ...
77539          Nos frangins 2022-05-23  299965.0     92.0        0        0
77540  Una notte da dottore 2021-10-28  299967.0     94.0        0        0
77541    L'Esprit Coubertin 2024-05-08  299968.0     78.0  2500000        0
77542         Ёлки лохматые 2015-01-29  299969.0     90.0        0  2234206
77543              Gone Mom 2021-06-05  300011.0     88.0        0        0

[77544 rows x 6 columns]

In [90]:
df_watchlist

           date                              name  year        letterboxd uri
0    2024-02-04      Colossus: The Forbin Project  1970  https://boxd.it/1Nmw
1    2024-02-04                               Her  2013  https://boxd.it/4O24
2    2024-02-04  Once Upon a Time... in Hollywood  2019  https://boxd.it/gH0O
3    2024-02-04                          Napoleon  2023  https://boxd.it/shJM
4    2024-02-04                     Asteroid City  2023  https://boxd.it/s3ds
..          ...                               ...   ...                   ...
348  2026-08-20                        The Chaser  2008  https://boxd.it/1PgU
349  2026-08-20                   I Saw the Devil  2010   https://boxd.it/FaK
350  2026-08-20                            Mother  2009  https://boxd.it/1m9g
351  2026-08-20                     The Innocents  2021  https://boxd.it/oAlc
352  2026-08-21                   Wild Horse Nine  2026  https://boxd.it/xG0M

[353 rows x 4 columns]

In [114]:
df_le = df_all_movies.copy()
df_le['year'] = df_le['date'].dt.year

df_watchlist_aug = (
    df_watchlist
    .merge(
        df_le.drop(columns='date'),
        how='left',
        on=['name', 'year']
        )
    .drop(columns='date')
)

# df_watchlist_aug[df_watchlist_aug['runtime']<90][['name','year','runtime','vote_average']]

df_watchlist_aug.sort_values(['year','runtime'],ascending=[False,True])[['name','year','runtime']]

                             name  year  runtime
342                Evil Dead Burn  2026    109.0
336                          Hope  2026    160.0
320              Dune: Part Three  2026      NaN
326                     Iron Lung  2026      NaN
330        Lee Cronin's The Mummy  2026      NaN
..                            ...   ...      ...
218                      Badlands  1973     94.0
0    Colossus: The Forbin Project  1970    100.0
215                    Easy Rider  1969     94.0
58                 Pierrot le Fou  1965    110.0
251  20,000 Leagues Under the Sea  1954    127.0

[353 rows x 3 columns]